#!/usr/bin/env bash
HOST=$(cat /etc/hostname)
for f in /home/domovoy/setup/*/ssh.pub; do
    dir=$(basename "$(dirname "$f")")
    [ "$dir" = "$HOST" ] && continue
    cat "$f"
done > /home/domovoy/.ssh/authorized_keys
